ARCH = arm
ARCH_LONG = armv5te
CPU = xscale
TUNE = xscale
OS = linux
LIBC = uclibc

packages-y = \
	toolchain/kernel-headers \
	toolchain/uclibc-headers \
	toolchain/binutils \
	toolchain/gcc-core \
	toolchain/uclibc \
	toolchain/gcc

