#!/bin/sh

sysroot=
prev=
args=
run=yes

while test "$#" -gt 0; do
	arg="$1"
	shift

	if [ "x$prev" != "x" ]; then
		eval "$prev=\"\$arg\""
		prev=
		continue
	fi

	case $arg in
		--sysroot)
			prev=sysroot
			;;

		--sysroot=*)
			sysroot=$(echo $arg | cut -d = -f 2-)
			;;

		--atleast-pkgconfig-version)
			args="$args $arg"
			run=no
			;;

		*)
			args="$args $arg"
			;;
	esac
done

if [ "x$run" = "xyes" -a "x$sysroot" != "x" ]; then
	/usr/bin/pkg-config --define-variable=prefix="$sysroot/usr" $args
else
	/usr/bin/pkg-config $args
fi

