#!/bin/sh -e

grep -v '^$' | grep -v '^#' | (
	while read toolchain; do
		if [ "x$1" = "xclean" ]; then
			scripts/build-toolchain $toolchain clean || exit $?
		else
			scripts/build-toolchain $toolchain || exit $?
		fi
	done
)
