#!/bin/sh

mkdir -p /etc
touch /etc/fstab
touch /etc/mdev.conf

echo -n "Mounting /proc filesystem ... "
mkdir -p /proc
mount -t proc none /proc
echo "done"

echo -n "Mounting /sys filesystem ... "
mkdir -p /sys
mount -t sysfs none /sys
echo "done"

echo -n "Populating /dev filesystem ... "
mdev -s
echo "done"

echo -n "Unblanking /dev/tty0 ... "
echo -ne "\033[9;0]" > /dev/tty0
echo "done"

/bin/run-parts -a start /etc/rcS.d

