#!/bin/sh

. /lib/lsb/init-functions

do_start() {
	# read hostname from /etc/hostname (if it exists)
	[ -f /etc/hostname ] && HOSTNAME=`cat /etc/hostname`

	# keep the current hostname otherwise
	[ -z "$HOSTNAME" ] && HOSTNAME=`hostname`

	log_action_begin_msg "Setting hostname to '$HOSTNAME' "
	hostname "$HOSTNAME"
	log_action_end_msg $?
}

case $1 in
	start)
		do_start
		;;

	stop)
		# no-op
		;;

	restart)
		do_start
		;;

	*)
		echo "usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

