#!/bin/sh

. /lib/lsb/init-functions

do_start() {
	log_action_begin_msg "Configuring network interfaces "
	ifup -a
	log_action_end_msg $?
}

do_stop() {
	log_action_begin_msg "Deconfiguring network interfaces "
	ifdown -a
	log_action_end_msg $?
}

case $1 in
	start)
		do_start
		;;

	stop)
		do_stop
		;;

	restart)
		do_stop
		do_start
		;;

	*)
		echo "usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

