#!/bin/sh

. /lib/lsb/init-functions

filter="grep -v '^#' | grep -v '^\s*\$' | xargs echo"

[ -f /etc/modules ] || exit 0

do_start() {
	echo "Loading modules ... "
	cat /etc/modules | eval $filter | (
		while read module; do
			log_action_begin_msg "  $module "
			modprobe $module
			log_action_end_msg $?
		done
	)
	echo "done"
}

do_stop() {
	echo "Unloading modules ... "
	cat /etc/modules | eval $filter | (
		while read module; do
			log_action_begin_msg "  $module "
			modprobe -r $module
			log_action_end_msg $?
		done
	)
	echo "done"
}

case $1 in
	start)
		do_start
		;;

	stop)
		do_stop
		;;

	restart)
		do_stop
		do_start
		;;

	*)
		echo "usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

