ARCH = arm
ARCH_LONG = armv4t
CPU = xscale
TUNE = strongarm110
OS = linux
LIBC = uclibc
FLOAT = soft
ABI = eabi
TARGET = $(ARCH)-$(CPU)-$(OS)-$(LIBC)$(ABI)
export ARCH ARCH_LONG CPU TUNE OS LIBC FLOAT ABI TARGET

LINUX_VERSION = 2.6.25.4
GCC_VERSION = 4.2.4
LIBC_VERSION = 0.9.29
export LINUX_VERSION GCC_VERSION LIBC_VERSION

