#!/bin/sh

if [ "x$1" = "x" ]; then
	echo "usage: $0 platform"
	exit 1
fi

platform="$1"

#find platform/$platform/rootfs -name '*.so*' -exec file {} + | \
#	grep -Rn 'not stripped' | cut -d: -f2

find platform/$platform/rootfs -executable -exec file {} + | \
	grep -Rn 'not stripped' | cut -d: -f2

