quiet_cmd_mkdir_p_arg = MKDIR     $2
      cmd_mkdir_p_arg = mkdir -p $2

quiet_cmd_extract_tar_bz2 = TAR [xj]  $(subst $(srctree)/,,$2)
      cmd_extract_tar_bz2 = cd $(tmptree); tar xjf $2; mkdir -p $(tmptree)/stamps; touch $(tmptree)/stamps/$(notdir $2)-extract

quiet_cmd_build_pkg = BUILD   $@
      cmd_build_pkg = $(Q)$(MAKE) $(package)=$@ build

# vim: ft=make

