src := $(obj)

include scripts/pbuild.mk

pbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))
include $(if $(wildcard $(pbuild-dir)/pbuild), $(pbuild-dir)/pbuild, $(pbuild-dir)/Makefile)

include scripts/Makefile.lib

ifndef obj
  $(warning pbuild: Makefile.initrd is included improperly)
endif

ARCH := $(patsubst i%86,x86,$(ARCH))

ifneq ($(wildcard scripts/Makefile.initrd-$(ARCH)),)
  include scripts/Makefile.initrd-$(ARCH)
else
  include scripts/Makefile.initrd-generic
endif

