src = $(obj)

PHONY := __build
__build:

obj-y :=

include scripts/Kbuild.include
include scripts/Makefile.lib

kbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))
kbuild-file := $(if $(wildcard $(kbuild-dir)/Kbuild),$(kbuild-dir)/Kbuild,$(kbuild-dir)/Makefile)
include $(kbuild-file)

packages-y = $(shell cat $(depends-file) | xargs echo)

PHONY += $(packages-y)
$(packages-y):
	@echo "building package $@"

__build: $(packages-y)

PHONY += FORCE
FORCE:

.PHONY: $(PHONY)
