#!/usr/bin/python

import string
import crypt
import sys

def rotn(char, num):
	lower = None
	upper = None

	if (char >= 'a') and (char <= 'z'):
		lower = 'a'
		upper = 'z'

	if (char >= 'A') and (char <= 'Z'):
		lower = 'A'
		upper = 'Z'

	if lower and upper:
		char = chr(ord(char) + num)
		while char < lower:
			char = chr(ord(char) + 26)

		while char > upper:
			char = chr(ord(char) - 26)

	return char;

def make_salt(string):
	one = rotn(string[0], -1)
	two = rotn(string[1], +1)
	return one + two

if len(sys.argv) < 2:
	print('usage: %s PASSWORD [SALT]' % sys.argv[0])
	sys.exit(1)

password = sys.argv[1]

if len(sys.argv) < 3:
	salt = make_salt(sys.argv[1])
else:
	salt = sys.argv[2]

print(crypt.crypt(password, salt))
