#!/bin/sh

packages="*.install"
version="current"

for arg in $@; do
	if [ "x$prev" != "x" ]; then
		if [ "x${arg#-}" != "x$arg" ]; then
			echo "WARNING: missing argument for parameter: $opt"
		else
			eval $prev=$arg
			prev=
			shift; continue
		fi
	fi

	opt=$arg

	case $arg in
		-a | --arch)
			prev=arch
			shift
			;;

		-l | --libc)
			prev=libc
			shift
			;;

		-r | --root)
			prev=root
			shift
			;;

		-v | --version)
			prev=version
			shift
			;;

		-b | --binary)
			prev=binary
			shift
			;;

		*)
			packages="$@"
			break
			;;
	esac
done

if [ "x$prev" != "x" ]; then
	echo "WARNING: missing argument for parameter: $opt"
fi

if [ "x$root" = "x" ]; then
	echo "ERROR: root directory was not specified - try using -r PATH"
	exit 1
fi

if [ ! -d "$root" ]; then
	echo "WARNING: root directory $root does not exist"
	mkdir -p "$root"
fi

cwd=`pwd`
base=`dirname $cwd`
name=`basename $cwd`

while [ "x$name" != "xpackages" ] && [ "x$name" != "xplatforms" ]; do
	if [ "x$name" = "x$base" ]; then
		break;
	fi

	base=`dirname $base`
	name=`basename $base`
done

pkg=${cwd#$base/}
base=`dirname $base`

if [ ! -f "$base/Makefile" ]; then
	echo "cannot find base directory"
	exit 1
fi

[ "x$binary" = "x" ] && binary="${base}/binary"
binary="${binary}/${arch}/${libc}/${pkg}"

for package in $packages; do
	package="${package%.install}"
	tarball="${package}_${version}_${arch}.tar.bz2"

	echo -n "Extracting binary package: $tarball ... "
	tar xjf "$binary/$tarball" -C "$root"
	echo "done"
done
