#!/bin/sh

packages="*.install"
version="current"

for arg in $@; do
	if [ "x$prev" != "x" ]; then
		if [ "x${arg#-}" = "x$arg" ]; then
			eval $prev=$arg
			prev=
			shift; continue
		else
			echo "WARNING: missing argument for parameter: $opt"
		fi
	fi

	opt=$arg

	case $arg in
		-a | --arch)
			prev=arch
			shift
			;;

		-l | --libc)
			prev=libc
			shift
			;;

		-v | --version)
			prev=version
			shift
			;;

		-b | --binary)
			prev=binary
			shift
			;;

		*)
			packages="$@"
			break
			;;
	esac
done

if [ "x$prev" != "x" ]; then
	echo "WARNING: missing argument for parameter: $opt"
fi

cwd=`pwd`
base=`dirname $cwd`
name=`basename $cwd`

while [ "x$name" != "xpackages" ] && [ "x$name" != "xplatforms" ]; do
	if [ "x$name" = "x$base" ]; then
		break;
	fi

	base=`dirname $base`
	name=`basename $base`
done

pkg=${cwd#$base/}
base=`dirname $base`

if [ ! -f "$base/Makefile" ]; then
	echo "cannot find base directory"
	exit 1
fi

[ "x$binary" = "x" ] && binary="${base}/binary"
binary="${binary}/${arch}/${libc}/${pkg}"
srcdir="${binary}/install"

for package in $packages; do
	package="${package%.install}"
	tarball="${package}_${version}_${arch}.tar.bz2"
	mkdir -p "${binary}"

	echo -n "Building binary package: $tarball ... "

	cat "$package.install" | (
		while read line; do
			[ "x${line#\#}" = "x$line" ] || continue

			src=`echo "$line" | awk '{ print $1 }'`
			dst=`echo "$line" | awk '{ print $2 }'`

			if [ "x$dst" = "x" ]; then
				dst=`dirname "$src"`
			fi

			if [ "x$dst" = "x/" ]; then
				dst="$src"
			fi

			src=${src#/}
			dst=${dst#/}

			echo "$dst"
		done
	) | tar cjpf "$binary/$tarball" -C "$srcdir/$package" -T -

	echo "done"
done
